import { validatePlatformDataset } from '../models/platform.js'

/** @type {import('../models/platform').PlatformDataset} */
export const PLATFORM_SEED_DATA = Object.freeze({
  projects: Object.freeze([
    Object.freeze({
      id: 'project_emperor_os',
      slug: 'emperor-os',
      name: 'Emperor_OS',
      status: 'active-legacy',
      adapterKey: 'emperor_os',
      supportsDeterministic: true,
      supportsAgentRuntime: true,
      supportsHumanSigning: true,
      legacyUrl: 'https://emperor-os.onrender.com/',
      description: 'Current operator-grade Mission Control workspace preserved as legacy executions experience.',
    }),
    Object.freeze({
      id: 'project_polymarket',
      slug: 'polymarket',
      name: 'Polymarket',
      status: 'planned',
      adapterKey: 'polymarket',
      supportsDeterministic: true,
      supportsAgentRuntime: true,
      supportsHumanSigning: false,
      description: 'Planned market-operations vertical. Scaffold records only in this phase.',
    }),
    Object.freeze({
      id: 'project_future_placeholder',
      slug: 'future-placeholder',
      name: 'Coming Soon',
      status: 'planned',
      adapterKey: 'future_placeholder',
      supportsDeterministic: false,
      supportsAgentRuntime: false,
      supportsHumanSigning: false,
      description: 'Reserved slot for future project vertical onboarding.',
    }),
  ]),
  runtimes: Object.freeze([
    Object.freeze({
      id: 'runtime_hermes_vps_main',
      name: 'Hermes VPS Main',
      provider: 'hermes',
      endpointType: 'ssh',
      status: 'connected',
      workspaceRoot: '/home/emperor/workspace',
      projectScopes: ['emperor-os', 'future-placeholder'],
      supportsDeterministicOps: true,
      supportsInteractiveAgentOps: true,
      supportsSigning: false,
    }),
    Object.freeze({
      id: 'runtime_openclaw_local',
      name: 'OpenClaw Local',
      provider: 'openclaw',
      endpointType: 'local',
      status: 'connected',
      workspaceRoot: '/home/emperor/workspace',
      projectScopes: ['emperor-os'],
      supportsDeterministicOps: true,
      supportsInteractiveAgentOps: true,
      supportsSigning: false,
    }),
    Object.freeze({
      id: 'runtime_hosted_placeholder',
      name: 'Hosted Runtime Placeholder',
      provider: 'future-hosted',
      endpointType: 'hosted',
      status: 'planned',
      workspaceRoot: '/home/emperor/workspace',
      projectScopes: ['polymarket', 'future-placeholder'],
      supportsDeterministicOps: false,
      supportsInteractiveAgentOps: false,
      supportsSigning: false,
    }),
  ]),
  skills: Object.freeze([
    Object.freeze({
      id: 'skill_det_artifact_packaging',
      slug: 'deterministic-artifact-packaging',
      name: 'deterministic artifact packaging',
      kind: 'deterministic',
      scope: 'platform',
      version: '1.0.0',
      status: 'active',
    }),
    Object.freeze({
      id: 'skill_ipfs_fetchback_verify',
      slug: 'ipfs-publish-fetchback-verify',
      name: 'IPFS publish + fetchback verify',
      kind: 'deterministic',
      scope: 'platform',
      version: '1.0.0',
      status: 'active',
    }),
    Object.freeze({
      id: 'skill_unsigned_tx_preview',
      slug: 'unsigned-tx-preview-generation',
      name: 'unsigned tx preview generation',
      kind: 'deterministic',
      scope: 'platform',
      version: '1.0.0',
      status: 'active',
    }),
    Object.freeze({
      id: 'skill_repo_triage_placeholder',
      slug: 'generic-repo-triage-placeholder',
      name: 'generic repo triage placeholder',
      kind: 'llm-assisted',
      scope: 'platform',
      version: '0.1.0',
      status: 'planned',
    }),
    Object.freeze({
      id: 'skill_emperor_procurement_helper_placeholder',
      slug: 'emperor-procurement-helper-placeholder',
      name: 'Emperor-specific procurement helper placeholder',
      kind: 'llm-assisted',
      scope: 'emperor_os',
      version: '0.1.0',
      status: 'planned',
    }),
  ]),
  executions: Object.freeze([
    Object.freeze({
      id: 'exec_20260420_001',
      projectId: 'project_emperor_os',
      runtimeId: 'runtime_hermes_vps_main',
      status: 'succeeded',
      deterministicStepCount: 11,
      llmCallCount: 1,
      approvalRequired: true,
      createdAt: '2026-04-20T20:00:00.000Z',
    }),
    Object.freeze({
      id: 'exec_20260420_002',
      projectId: 'project_emperor_os',
      runtimeId: 'runtime_openclaw_local',
      status: 'awaiting_review',
      deterministicStepCount: 7,
      llmCallCount: 0,
      approvalRequired: true,
      createdAt: '2026-04-20T20:30:00.000Z',
    }),
    Object.freeze({
      id: 'exec_20260420_003',
      projectId: 'project_polymarket',
      runtimeId: 'runtime_hosted_placeholder',
      status: 'queued',
      deterministicStepCount: 2,
      llmCallCount: 0,
      approvalRequired: true,
      createdAt: '2026-04-20T21:00:00.000Z',
    }),
  ]),
})

const validation = validatePlatformDataset(PLATFORM_SEED_DATA)
if (!validation.ok) {
  throw new Error('Invalid PLATFORM_SEED_DATA:\n' + validation.errors.join('\n'))
}
