export const V1_TRANSITIONS = {
  DISCOVERED: ["EVALUATED", "BLOCKED_RETRIEVAL_REQUIRED", "FAILED"],
  EVALUATED: ["APPLY_READY", "FAILED"],
  APPLY_READY: ["APPLIED_UNSIGNED", "BLOCKED_OPERATOR_REVIEW", "FAILED"],
  APPLIED_UNSIGNED: ["APPLIED_CONFIRMED", "BLOCKED_OPERATOR_REVIEW", "FAILED"],
  APPLIED_CONFIRMED: ["EXECUTION_READY", "FAILED"],
  EXECUTION_READY: ["EXECUTED", "BLOCKED_RETRIEVAL_REQUIRED", "FAILED"],
  EXECUTED: ["VALIDATED", "FAILED"],
  VALIDATED: ["PUBLISHED", "FAILED"],
  PUBLISHED: ["SUBMISSION_READY", "BLOCKED_ARTIFACT_EMISSION_REQUIRED", "FAILED"],
  SUBMISSION_READY: ["SUBMITTED_UNSIGNED", "BLOCKED_OPERATOR_REVIEW", "FAILED"],
  SUBMITTED_UNSIGNED: ["RECONCILING", "BLOCKED_OPERATOR_REVIEW", "FAILED"],
  RECONCILING: ["DONE", "FAILED"],
  BLOCKED_RETRIEVAL_REQUIRED: ["DISCOVERED", "EXECUTION_READY", "FAILED"],
  BLOCKED_OPERATOR_REVIEW: ["APPLY_READY", "SUBMISSION_READY", "FAILED"],
  BLOCKED_ARTIFACT_EMISSION_REQUIRED: ["PUBLISHED", "FAILED"],
  FAILED: [],
  DONE: []
};
