export const V1_STATES = [
  "DISCOVERED",
  "EVALUATED",
  "APPLY_READY",
  "APPLIED_UNSIGNED",
  "APPLIED_CONFIRMED",
  "EXECUTION_READY",
  "EXECUTED",
  "VALIDATED",
  "PUBLISHED",
  "SUBMISSION_READY",
  "SUBMITTED_UNSIGNED",
  "RECONCILING",
  "DONE",
  "FAILED",
  "BLOCKED_RETRIEVAL_REQUIRED",
  "BLOCKED_OPERATOR_REVIEW",
  "BLOCKED_ARTIFACT_EMISSION_REQUIRED"
];

export const V1_TERMINAL = new Set(["DONE", "FAILED"]);
